project:
  type: book

book:
  title: "Linux based working environment"
  author: "Moinul Islam"
  date: "today"
  chapters:
    - index.qmd
    - linux.qmd
    - emacs.qmd
    - stata.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

